;this file for FamiTone2 library generated by FamiStudio


FT_DPCM_PTR=$c000
          .export _journey_to_silius_music_data
_journey_to_silius_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256




@instruments:
	.byte $30 ;instrument 00 (LeadDuty0Buzz)
	.word @env4, @env0, @env3
	.byte $00
	.byte $30 ;instrument 01 (LeadDuty0Main)
	.word @env13, @env0, @env3
	.byte $00
	.byte $30 ;instrument 02 (LeadDuty0Outro)
	.word @env1, @env0, @env0
	.byte $00
	.byte $30 ;instrument 03 (LeadDuty0Plain)
	.word @env8, @env0, @env0
	.byte $00
	.byte $70 ;instrument 04 (LeadDuty1Main)
	.word @env13, @env0, @env3
	.byte $00
	.byte $70 ;instrument 05 (LeadDuty1Plain)
	.word @env2, @env0, @env0
	.byte $00
	.byte $b0 ;instrument 06 (LeadDuty2Main)
	.word @env12, @env0, @env3
	.byte $00
	.byte $b0 ;instrument 07 (LeadDuty2Plain)
	.word @env8, @env0, @env0
	.byte $00
	.byte $30 ;instrument 08 (NoiseTom1)
	.word @env6, @env10, @env0
	.byte $00
	.byte $30 ;instrument 09 (NoiseTom2)
	.word @env7, @env11, @env0
	.byte $00
	.byte $30 ;instrument 0a (NoiseTom3)
	.word @env6, @env11, @env0
	.byte $00
	.byte $30 ;instrument 0b (TriTomArp)
	.word @env5, @env9, @env0
	.byte $00
	.byte $30 ;instrument 0c (TriTomPlain)
	.word @env5, @env0, @env0
	.byte $00

@samples:
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;1 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;2 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;3 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;4 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;5 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;6 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;7 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;8 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;9 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;10 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;11 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;12 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;13 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;14 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;15 
	.byte $00+.lobyte(FT_DPCM_PTR),$3e,$08	;16 (Sample 2)
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;17 
	.byte $10+.lobyte(FT_DPCM_PTR),$3f,$09	;18 (Sample 1)
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;19 
	.byte $10+.lobyte(FT_DPCM_PTR),$3f,$0a	;20 (Sample 1)
	.byte $00+.lobyte(FT_DPCM_PTR),$3e,$0a	;21 (Sample 2)
	.byte $20+.lobyte(FT_DPCM_PTR),$3f,$0a	;22 (Sample 5)
	.byte $30+.lobyte(FT_DPCM_PTR),$3e,$0c	;23 (Sample 4)
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;24 
	.byte $10+.lobyte(FT_DPCM_PTR),$3f,$0c	;25 (Sample 1)
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;26 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;27 
	.byte $40+.lobyte(FT_DPCM_PTR),$3f,$0d	;28 (Sample 3)
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;29 
	.byte $00+.lobyte(FT_DPCM_PTR),$3e,$0d	;30 (Sample 2)
	.byte $40+.lobyte(FT_DPCM_PTR),$3f,$0e	;31 (Sample 3)
	.byte $10+.lobyte(FT_DPCM_PTR),$3f,$0e	;32 (Sample 1)
	.byte $00+.lobyte(FT_DPCM_PTR),$3e,$0e	;33 (Sample 2)
	.byte $20+.lobyte(FT_DPCM_PTR),$3f,$0e	;34 (Sample 5)
	.byte $30+.lobyte(FT_DPCM_PTR),$3e,$0f	;35 (Sample 4)
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;36 
	.byte $10+.lobyte(FT_DPCM_PTR),$3f,$0f	;37 (Sample 1)
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;38 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;39 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;40 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;41 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;42 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;43 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;44 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;45 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;46 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;47 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;48 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;49 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;50 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;51 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;52 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;53 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;54 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;55 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;56 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;57 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;58 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;59 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;60 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;61 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;62 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;63 

@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $c5,$c9,$c9,$c8,$00,$03
@env2:
	.byte $c3,$7f,$00,$00
@env3:
	.byte $c0,$07,$c1,$c3,$c6,$c3,$c1,$bf,$bd,$ba,$bd,$bf,$00,$02
@env4:
	.byte $ce,$cb,$ca,$c9,$c9,$00,$04
@env5:
	.byte $cf,$7f,$00,$00
@env6:
	.byte $cc,$cc,$c9,$c5,$c2,$c0,$00,$05
@env7:
	.byte $cd,$ce,$cc,$c8,$c9,$c7,$c6,$c4,$c3,$c1,$c0,$00,$0a
@env8:
	.byte $c4,$7f,$00,$00
@env9:
	.byte $c0,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$00,$09
@env10:
	.byte $c0,$c3,$00,$01
@env11:
	.byte $c0,$c6,$00,$01
@env12:
	.byte $c5,$c6,$c6,$ca,$cb,$cc,$cb,$ca,$c9,$c8,$c7,$00,$0a
@env13:
	.byte $c4,$c6,$c9,$c8,$0e,$c7,$0e,$c6,$0e,$c5,$0e,$c4,$00,$0b

@song0ch0:
	.byte $fb, $01
@ref0:
	.byte $cf
@song0ch0loop:
@ref1:
	.byte $00,$a5,$8a,$32,$91,$38,$91,$32,$91,$3c,$3f,$40,$9f,$3c,$91
@ref2:
	.byte $82,$28,$b9,$2c,$e1
	.byte $ff,$0e
	.word @ref1
@ref3:
	.byte $82,$40,$b9,$3c,$e1
	.byte $ff,$0e
	.word @ref1
	.byte $ff,$04
	.word @ref2
	.byte $ff,$0e
	.word @ref1
	.byte $ff,$04
	.word @ref3
@ref4:
	.byte $a7,$2e,$a5,$2c,$91,$2e,$a5,$2e,$91
@ref5:
	.byte $a7,$2c,$a5,$2c,$91,$2e,$b9
	.byte $ff,$09
	.word @ref4
	.byte $ff,$07
	.word @ref5
	.byte $ff,$09
	.word @ref4
	.byte $ff,$07
	.word @ref5
@ref6:
	.byte $a7,$2e,$a5,$2c,$91,$2e,$a5,$28,$91
@ref7:
	.byte $f9,$91,$8c,$32,$91
@ref8:
	.byte $93,$32,$91,$38,$91,$32,$91,$3c,$91,$32,$a5,$40,$91
@ref9:
	.byte $93,$32,$91,$3c,$91,$32,$91,$38,$91,$32,$a5,$28,$91
@ref10:
	.byte $93,$28,$91,$2e,$91,$28,$91,$2e,$91,$34,$37,$38,$8b,$36,$91,$32,$91
@ref11:
	.byte $f9,$91,$32,$91
@ref12:
	.byte $93,$32,$91,$38,$91,$32,$91,$3c,$91,$32,$a5,$3c,$3f,$40,$8b
	.byte $ff,$0d
	.word @ref9
@ref13:
	.byte $93,$28,$91,$2e,$91,$32,$91,$34,$37,$38,$8b,$36,$91,$2e,$91,$32,$91
@ref14:
	.byte $f9,$a5
@ref15:
	.byte $3d,$3f,$40,$d9,$3c,$91,$38,$91,$36,$91
@ref16:
	.byte $cf,$38,$9b,$3c,$9b,$3c,$3f,$40,$8b
@ref17:
	.byte $f9,$91,$88,$3c,$3f,$40,$8b
@ref18:
	.byte $93,$3c,$3f,$40,$8b,$44,$a5,$46,$cd
@ref19:
	.byte $8c,$3d,$3f,$40,$d9,$3c,$91,$38,$91,$36,$91
@ref20:
	.byte $cf,$38,$9b,$3c,$9b,$32,$91
@ref21:
	.byte $f9,$a5
@ref22:
	.byte $93,$80,$32,$91,$32,$91,$32,$91,$32,$cd
@ref23:
	.byte $82,$32,$cd,$32,$cd
@ref24:
	.byte $32,$b9,$32,$e1
@ref25:
	.byte $32,$cd,$32,$cd
@ref26:
	.byte $32,$b9,$32,$e1
@ref27:
	.byte $32,$cd,$32,$cd
@ref28:
	.byte $32,$b9,$32,$e1
@ref29:
	.byte $36,$cd,$36,$cd
@ref30:
	.byte $36,$b9,$36,$e1
@ref31:
	.byte $32,$a5,$32,$a5,$32,$9b,$32,$9b,$32,$91
@ref32:
	.byte $a7,$32,$a5,$32,$9b,$32,$9b,$32,$91
	.byte $ff,$09
	.word @ref32
@ref33:
	.byte $bb,$2e,$cd,$32,$91
	.byte $ff,$09
	.word @ref32
	.byte $ff,$09
	.word @ref32
@ref34:
	.byte $a7,$32,$a5,$36,$9b,$40,$9b,$40,$91
@ref35:
	.byte $f9,$a5
@ref36:
	.byte $00,$a5,$86,$32,$91,$36,$91,$38,$91,$3c,$91,$32,$91,$36,$91
@ref37:
	.byte $38,$91,$3c,$91,$32,$91,$36,$91,$38,$91,$3c,$91,$32,$91,$36,$91
	.byte $ff,$10
	.word @ref37
	.byte $ff,$10
	.word @ref37
	.byte $ff,$10
	.word @ref37
@ref38:
	.byte $38,$91,$3c,$91,$36,$91,$38,$91,$3c,$91,$40,$b9
@ref39:
	.byte $46,$91,$4a,$a5,$4e,$91,$50,$91,$54,$91,$4a,$91,$4e,$91
@ref40:
	.byte $50,$91,$54,$a5,$58,$91,$5a,$91,$5e,$91,$54,$91,$58,$91
@ref41:
	.byte $5a,$91,$5e,$91,$62,$f5
@ref42:
	.byte $f7,$62,$a5
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@ref43:
	.byte $cf
@song0ch1loop:
@ref44:
	.byte $88,$32,$91,$38,$91,$32,$91,$3c,$3f,$40,$9f,$3c,$91,$38,$a5
@ref45:
	.byte $2e,$b9,$32,$e1
@ref46:
	.byte $32,$91,$38,$91,$32,$91,$3c,$3f,$40,$9f,$3c,$91,$38,$a5
@ref47:
	.byte $46,$b9,$44,$e1
	.byte $ff,$0e
	.word @ref46
@ref48:
	.byte $2e,$b9,$32,$e1
	.byte $ff,$0e
	.word @ref46
@ref49:
	.byte $46,$b9,$44,$e1
@ref50:
	.byte $a7,$82,$38,$a5,$36,$91,$38,$a5,$38,$91
@ref51:
	.byte $a7,$36,$a5,$36,$91,$38,$b9
@ref52:
	.byte $a7,$38,$a5,$36,$91,$38,$a5,$38,$91
	.byte $ff,$07
	.word @ref51
	.byte $ff,$09
	.word @ref52
	.byte $ff,$07
	.word @ref51
@ref53:
	.byte $a7,$38,$a5,$36,$91,$38,$a5,$36,$91
@ref54:
	.byte $f9,$a5
@ref55:
	.byte $93,$8e,$32,$b9,$38,$91,$32,$91,$3c,$91,$32,$91
@ref56:
	.byte $93,$40,$a5,$32,$91,$3c,$91,$32,$91,$38,$91,$32,$91
@ref57:
	.byte $93,$28,$b9,$2e,$91,$28,$91,$2e,$91,$34,$37,$38,$8b
@ref58:
	.byte $36,$91,$32,$f9,$8f
@ref59:
	.byte $cf,$38,$91,$32,$91,$3c,$91,$32,$91
@ref60:
	.byte $93,$3c,$3f,$40,$9f,$32,$91,$3c,$91,$32,$91,$38,$91,$32,$91
@ref61:
	.byte $93,$28,$b9,$2e,$91,$32,$91,$34,$37,$38,$8b,$36,$91
@ref62:
	.byte $2e,$91,$32,$f9,$8f
@ref63:
	.byte $a7,$3d,$3f,$40,$d9,$3c,$91
@ref64:
	.byte $38,$91,$36,$e1,$38,$9b,$3c,$87
@ref65:
	.byte $95,$3f,$40,$ef,$82,$36,$91
@ref66:
	.byte $93,$36,$91,$3c,$a5,$40,$cd
@ref67:
	.byte $a7,$8e,$3d,$3f,$40,$d9,$3c,$91
	.byte $ff,$08
	.word @ref64
@ref68:
	.byte $93,$32,$f9,$8f
@ref69:
	.byte $93,$80,$28,$91,$28,$91,$28,$91,$28,$cd
@ref70:
	.byte $88,$40,$cd,$3c,$cd
@ref71:
	.byte $38,$b9,$3c,$e1
@ref72:
	.byte $40,$cd,$3c,$cd
@ref73:
	.byte $38,$b9,$3c,$e1
@ref74:
	.byte $40,$cd,$3c,$cd
@ref75:
	.byte $38,$b9,$3c,$e1
@ref76:
	.byte $42,$cd,$40,$cd
@ref77:
	.byte $3c,$b9,$40,$e1
@ref78:
	.byte $40,$a5,$3c,$a5,$38,$9b,$3c,$9b,$40,$91
@ref79:
	.byte $a7,$3c,$a5,$38,$9b,$3c,$9b,$40,$91
@ref80:
	.byte $a7,$3c,$a5,$38,$9b,$3c,$9b,$38,$91
@ref81:
	.byte $bb,$36,$cd,$40,$91
	.byte $ff,$09
	.word @ref79
	.byte $ff,$09
	.word @ref79
@ref82:
	.byte $a7,$3c,$a5,$40,$9b,$46,$9b,$4a,$91
@ref83:
	.byte $f9,$a5
@ref84:
	.byte $84,$32,$91,$36,$91,$38,$91,$3c,$91,$32,$91,$36,$91,$38,$91,$3c,$91
@ref85:
	.byte $32,$91,$36,$91,$38,$91,$3c,$91,$32,$91,$36,$91,$38,$91,$3c,$91
	.byte $ff,$10
	.word @ref85
	.byte $ff,$10
	.word @ref85
	.byte $ff,$10
	.word @ref85
@ref86:
	.byte $36,$91,$38,$91,$3c,$91,$40,$b9,$46,$91,$4a,$91
@ref87:
	.byte $93,$4e,$91,$50,$91,$54,$91,$4a,$91,$4e,$91,$50,$91,$54,$91
@ref88:
	.byte $93,$58,$91,$5a,$91,$5e,$91,$54,$91,$58,$91,$5a,$91,$5e,$91
@ref89:
	.byte $62,$f9,$a3
@ref90:
	.byte $cf,$62,$cd
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@ref91:
	.byte $98,$4c,$4a,$4d,$4a,$4c,$4e,$4c,$4a,$4c,$96,$4c,$85,$00,$4c,$85,$00,$3c,$85,$00,$3c,$85,$00,$34,$8f,$00
@song0ch2loop:
@ref92:
	.byte $96,$38,$83,$00,$8b,$38,$83,$00,$8b,$44,$8f,$00,$38,$83,$00,$8b,$38,$83,$00,$8b,$38,$83,$00,$8b,$44,$8f,$00,$38,$83,$00,$8b
@ref93:
	.byte $38,$83,$00,$8b,$38,$83,$00,$8b,$44,$8f,$00,$38,$83,$00,$8b,$38,$83,$00,$8b,$38,$83,$00,$8b,$44,$8f,$00,$38,$83,$00,$8b
	.byte $ff,$1e
	.word @ref93
@ref94:
	.byte $4c,$8f,$00,$4c,$8f,$00,$3c,$8f,$00,$34,$8f,$00,$4c,$85,$00,$4c,$85,$00,$89,$4c,$85,$00,$3c,$85,$00,$3c,$85,$00,$34,$8f,$00
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1e
	.word @ref93
@ref95:
	.byte $4c,$85,$00,$4c,$85,$00,$3c,$85,$00,$34,$85,$00,$4c,$85,$00,$3c,$85,$00,$3c,$85,$00,$34,$85,$00,$98,$4c,$4a,$4d,$4a,$4c,$4e,$4c,$4a,$4c,$96,$4c,$85,$00,$4c,$85,$00,$3c,$85,$00,$3c,$85,$00,$34,$85,$00,$34,$85,$00
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1f
	.word @ref94
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$33
	.word @ref95
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1f
	.word @ref94
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$33
	.word @ref95
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1f
	.word @ref94
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1e
	.word @ref93
@ref96:
	.byte $38,$83,$00,$8b,$44,$8f,$00,$44,$8f,$00,$44,$8f,$00,$44,$8f,$00,$95,$98,$44,$83,$00,$9d
@ref97:
	.byte $96,$38,$83,$00,$c7,$38,$83,$00,$c7
@ref98:
	.byte $38,$83,$00,$b3,$38,$83,$00,$9f,$98,$44,$83,$00,$8b,$96,$38,$83,$00,$9f
@ref99:
	.byte $38,$83,$00,$c7,$38,$83,$00,$c7
	.byte $ff,$10
	.word @ref98
	.byte $ff,$08
	.word @ref99
	.byte $ff,$10
	.word @ref98
	.byte $ff,$08
	.word @ref99
@ref100:
	.byte $38,$83,$00,$b3,$38,$83,$00,$9f,$44,$8f,$00,$44,$8f,$00,$44,$8f,$00
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1f
	.word @ref94
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$33
	.word @ref95
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1f
	.word @ref94
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$33
	.word @ref95
	.byte $ff,$1e
	.word @ref93
	.byte $ff,$33
	.word @ref95
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@ref101:
	.byte $92,$4c,$83,$4c,$85,$4c,$83,$4c,$87,$4c,$87,$4c,$87,$4c,$87,$4c,$87,$4c,$87
@song0ch3loop:
@ref102:
	.byte $90,$38,$91,$38,$91,$92,$4c,$91,$90,$38,$91,$38,$91,$38,$91,$92,$4c,$91,$90,$38,$91
@ref103:
	.byte $38,$91,$38,$91,$92,$4c,$91,$90,$38,$91,$38,$91,$38,$91,$92,$4c,$91,$90,$38,$91
	.byte $ff,$10
	.word @ref103
@ref104:
	.byte $94,$4c,$91,$4c,$91,$4c,$91,$4c,$91,$4c,$87,$4c,$91,$4c,$87,$4c,$87,$4c,$87,$4c,$91
	.byte $ff,$10
	.word @ref102
	.byte $ff,$10
	.word @ref103
	.byte $ff,$10
	.word @ref103
@ref105:
	.byte $94,$4c,$87,$4c,$87,$4c,$87,$4c,$87,$4c,$87,$4c,$87,$4c,$87,$4c,$87,$4c,$87,$4c,$87,$4c,$87,$4c,$87,$4c,$87,$4c,$87,$4c,$87,$4c,$87
	.byte $ff,$10
	.word @ref102
	.byte $ff,$10
	.word @ref103
	.byte $ff,$10
	.word @ref103
	.byte $ff,$14
	.word @ref104
	.byte $ff,$10
	.word @ref102
	.byte $ff,$10
	.word @ref103
	.byte $ff,$10
	.word @ref103
	.byte $ff,$20
	.word @ref105
	.byte $ff,$10
	.word @ref102
	.byte $ff,$10
	.word @ref103
	.byte $ff,$10
	.word @ref103
	.byte $ff,$14
	.word @ref104
	.byte $ff,$10
	.word @ref102
	.byte $ff,$10
	.word @ref103
	.byte $ff,$10
	.word @ref103
	.byte $ff,$20
	.word @ref105
	.byte $ff,$10
	.word @ref102
	.byte $ff,$10
	.word @ref103
	.byte $ff,$10
	.word @ref103
	.byte $ff,$14
	.word @ref104
	.byte $ff,$10
	.word @ref102
	.byte $ff,$10
	.word @ref103
	.byte $ff,$10
	.word @ref103
@ref106:
	.byte $38,$91,$92,$4c,$91,$4c,$91,$4c,$91,$4c,$a7,$4c,$a3
@ref107:
	.byte $90,$38,$cd,$38,$cd
@ref108:
	.byte $38,$b9,$38,$a5,$92,$4c,$91,$90,$38,$a5
@ref109:
	.byte $38,$cd,$38,$cd
	.byte $ff,$08
	.word @ref108
@ref110:
	.byte $38,$cd,$38,$cd
	.byte $ff,$08
	.word @ref108
@ref111:
	.byte $38,$cd,$38,$cd
@ref112:
	.byte $38,$b9,$38,$a5,$92,$4c,$91,$4c,$91,$4c,$91
	.byte $ff,$10
	.word @ref102
	.byte $ff,$10
	.word @ref103
	.byte $ff,$10
	.word @ref103
	.byte $ff,$14
	.word @ref104
	.byte $ff,$10
	.word @ref102
	.byte $ff,$10
	.word @ref103
	.byte $ff,$10
	.word @ref103
	.byte $ff,$20
	.word @ref105
	.byte $ff,$10
	.word @ref102
	.byte $ff,$10
	.word @ref103
	.byte $ff,$10
	.word @ref103
	.byte $ff,$14
	.word @ref104
	.byte $ff,$10
	.word @ref102
	.byte $ff,$10
	.word @ref103
	.byte $ff,$10
	.word @ref103
	.byte $ff,$20
	.word @ref105
	.byte $ff,$10
	.word @ref102
	.byte $ff,$20
	.word @ref105
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@ref113:
	.byte $cf
@song0ch4loop:
@ref114:
	.byte $32,$91,$32,$91,$32,$91,$32,$91,$32,$91,$32,$91,$32,$91,$32,$91
@ref115:
	.byte $28,$91,$28,$91,$40,$91,$24,$91,$24,$91,$3c,$91,$24,$91,$3c,$91
	.byte $ff,$10
	.word @ref114
@ref116:
	.byte $20,$91,$20,$91,$38,$91,$24,$91,$24,$91,$3c,$91,$24,$91,$3c,$91
	.byte $ff,$10
	.word @ref114
	.byte $ff,$10
	.word @ref115
	.byte $ff,$10
	.word @ref114
	.byte $ff,$10
	.word @ref116
	.byte $ff,$10
	.word @ref114
	.byte $ff,$10
	.word @ref114
	.byte $ff,$10
	.word @ref114
	.byte $ff,$10
	.word @ref114
	.byte $ff,$10
	.word @ref114
	.byte $ff,$10
	.word @ref114
@ref117:
	.byte $32,$91,$32,$91,$32,$91,$32,$91,$32,$91,$32,$91,$32,$91,$28,$91
@ref118:
	.byte $28,$91,$28,$91,$28,$91,$28,$91,$28,$91,$28,$91,$28,$91,$28,$91
@ref119:
	.byte $32,$91,$32,$91,$32,$91,$4a,$91,$32,$91,$4a,$91,$32,$91,$32,$91
@ref120:
	.byte $2e,$91,$46,$91,$2e,$91,$2e,$91,$2e,$91,$46,$91,$2e,$91,$2e,$91
@ref121:
	.byte $28,$91,$28,$91,$28,$91,$40,$91,$2e,$91,$46,$91,$2e,$91,$2e,$91
@ref122:
	.byte $32,$91,$4a,$91,$32,$91,$32,$91,$32,$91,$4a,$91,$32,$91,$32,$91
	.byte $ff,$10
	.word @ref119
	.byte $ff,$10
	.word @ref120
	.byte $ff,$10
	.word @ref121
	.byte $ff,$10
	.word @ref122
@ref123:
	.byte $24,$91,$24,$91,$3c,$91,$24,$91,$24,$91,$24,$91,$3c,$91,$24,$91
@ref124:
	.byte $28,$91,$28,$91,$40,$91,$28,$91,$28,$91,$28,$91,$40,$91,$28,$91
@ref125:
	.byte $32,$91,$32,$91,$4a,$91,$32,$91,$4a,$91,$32,$91,$32,$91,$4a,$91
@ref126:
	.byte $32,$91,$32,$91,$4a,$91,$32,$91,$32,$91,$4a,$91,$32,$91,$4a,$91
	.byte $ff,$10
	.word @ref123
	.byte $ff,$10
	.word @ref124
	.byte $ff,$10
	.word @ref125
@ref127:
	.byte $32,$91,$32,$91,$32,$91,$32,$91,$32,$cd
@ref128:
	.byte $32,$cd,$32,$cd
@ref129:
	.byte $32,$b9,$32,$a5,$32,$91,$4a,$91,$32,$91
@ref130:
	.byte $2e,$cd,$2e,$cd
@ref131:
	.byte $2e,$b9,$2e,$a5,$2e,$91,$46,$91,$2e,$91
@ref132:
	.byte $2a,$cd,$2a,$cd
@ref133:
	.byte $2a,$b9,$2a,$a5,$2a,$91,$46,$91,$2a,$91
@ref134:
	.byte $2e,$cd,$2e,$cd
@ref135:
	.byte $2e,$b9,$2e,$a5,$46,$91,$2e,$91,$46,$91
	.byte $ff,$10
	.word @ref126
@ref136:
	.byte $2e,$91,$2e,$91,$46,$91,$2e,$91,$2e,$91,$46,$91,$2e,$91,$46,$91
@ref137:
	.byte $2a,$91,$2a,$91,$42,$91,$2a,$91,$2a,$91,$42,$91,$2a,$91,$42,$91
	.byte $ff,$10
	.word @ref136
	.byte $ff,$10
	.word @ref126
	.byte $ff,$10
	.word @ref136
	.byte $ff,$10
	.word @ref137
	.byte $ff,$10
	.word @ref126
@ref138:
	.byte $32,$91,$32,$91,$32,$91,$4a,$91,$32,$91,$32,$91,$46,$91,$4a,$91
@ref139:
	.byte $2e,$91,$2e,$91,$2e,$91,$46,$91,$2e,$91,$2e,$91,$42,$91,$46,$91
@ref140:
	.byte $2c,$91,$2c,$91,$2c,$91,$44,$91,$2c,$91,$2c,$91,$28,$91,$44,$91
@ref141:
	.byte $2a,$91,$2a,$91,$2a,$91,$42,$91,$2a,$91,$2a,$91,$3e,$91,$42,$91
	.byte $ff,$10
	.word @ref138
	.byte $ff,$10
	.word @ref139
	.byte $ff,$10
	.word @ref140
	.byte $ff,$10
	.word @ref141
	.byte $ff,$10
	.word @ref138
	.byte $ff,$10
	.word @ref126
	.byte $fd
	.word @song0ch4loop
