;this file for FamiTone2 library generated by FamiStudio
FT_DPCM_PTR=$c000
  .export _megalovania_music_data
_megalovania_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256




@instruments:
	.byte $30 ;instrument 00 (Duty 0)
	.word @env1, @env0, @env0
	.byte $00
	.byte $70 ;instrument 01 (Duty 1)
	.word @env1, @env0, @env0
	.byte $00
	.byte $b0 ;instrument 02 (Duty 2)
	.word @env1, @env0, @env0
	.byte $00

@samples:
@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $cf,$7f,$00,$00

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
@ref0:
	.byte $80,$1e,$9b,$36,$9b,$2c,$a9,$2a,$95
@ref1:
	.byte $85,$28,$9b,$24,$9b,$1e,$8d,$24,$8b,$28,$8d,$1a,$8d
@ref2:
	.byte $8d,$36,$9b,$2c,$a9,$2a,$9b,$28,$87
@ref3:
	.byte $93,$24,$9b,$1e,$8d,$24,$8b,$28,$8d,$18,$9b,$36
@ref4:
	.byte $9b,$2c,$a9,$2a,$9b,$28,$97
@ref5:
	.byte $83,$24,$9b,$1e,$8d,$24,$8b,$28,$8d,$16,$9b,$36,$8f
@ref6:
	.byte $8b,$2c,$a9,$2a,$9b,$28,$9b,$24,$89
@ref7:
	.byte $bf,$1e,$9b,$36,$9b,$2c,$81
@ref8:
	.byte $a7,$2a,$9b,$28,$9b,$24,$99
@ref9:
	.byte $81,$1e,$8d,$24,$8b,$28,$8d,$1a,$9b,$36,$9b,$2c,$91
@ref10:
	.byte $97,$2a,$9b,$28,$9b,$24,$9b,$1e,$8b
@ref11:
	.byte $81,$24,$8b,$28,$8d,$18,$9b,$36,$9b,$2c,$a1
@ref12:
	.byte $87,$2a,$9b,$28,$9b,$24,$9b,$1e,$8d,$24,$8b
@ref13:
	.byte $28,$8d,$16,$9b,$36,$9b,$2c,$a9,$2a,$85
@ref14:
	.byte $95,$28,$9b,$32,$8f,$35,$32,$83,$30,$83,$32,$83,$35,$32,$83,$31,$32,$93
@ref15:
	.byte $28,$9b,$2c,$9b,$30,$9b,$32,$a3
@ref16:
	.byte $95,$36,$9b,$3a,$b9,$2a,$8d
@ref17:
	.byte $f9,$85
@ref18:
	.byte $df,$2c,$9b,$24
@ref19:
	.byte $9b,$2c,$9b,$28,$c3
@ref20:
	.byte $bf,$2a,$8d,$2c,$9b,$24,$8f
@ref21:
	.byte $a9,$2c,$8b,$28,$b9,$32,$89
@ref22:
	.byte $83,$30,$8b,$32,$8d,$30,$8b,$32,$8d,$28,$9b,$2c,$9b,$30,$81
@ref23:
	.byte $99,$32,$b9,$36,$9b,$3a,$89
@ref24:
	.byte $af,$2a,$cd
@ref25:
	.byte $f9,$85
@ref26:
	.byte $9f,$2c,$9b,$24,$9b,$2c,$9b,$28,$83
@ref27:
	.byte $f9,$85
@ref28:
	.byte $2a,$8d,$2c,$9b,$24,$b9,$2c,$8b,$28,$85
@ref29:
	.byte $b3,$32,$8d,$30,$8b,$32,$8d,$30,$8b,$32,$8d
	.byte $ff,$08
	.word @ref15
	.byte $ff,$07
	.word @ref16
@ref30:
	.byte $f9,$85
@ref31:
	.byte $df,$2c,$9b,$24
	.byte $ff,$05
	.word @ref19
	.byte $ff,$07
	.word @ref20
	.byte $ff,$07
	.word @ref21
	.byte $ff,$0f
	.word @ref22
	.byte $ff,$07
	.word @ref23
@ref32:
	.byte $af,$2a,$cd
@ref33:
	.byte $f9,$85
	.byte $ff,$09
	.word @ref26
@ref34:
	.byte $f9,$85
	.byte $ff,$0a
	.word @ref28
	.byte $ff,$0b
	.word @ref29
	.byte $ff,$08
	.word @ref15
	.byte $ff,$07
	.word @ref16
@ref35:
	.byte $f9,$85
@ref36:
	.byte $df,$2c,$9b,$24
	.byte $ff,$05
	.word @ref19
	.byte $ff,$07
	.word @ref20
	.byte $ff,$07
	.word @ref21
	.byte $ff,$0f
	.word @ref22
	.byte $ff,$07
	.word @ref23
@ref37:
	.byte $af,$2a,$cd
@ref38:
	.byte $f9,$85
	.byte $ff,$09
	.word @ref26
@ref39:
	.byte $f9,$85
	.byte $ff,$0a
	.word @ref28
	.byte $ff,$0b
	.word @ref29
	.byte $ff,$08
	.word @ref15
	.byte $ff,$07
	.word @ref16
@ref40:
	.byte $f9,$85
@ref41:
	.byte $df,$2c,$9b,$24
	.byte $ff,$05
	.word @ref19
	.byte $ff,$07
	.word @ref20
	.byte $ff,$07
	.word @ref21
	.byte $ff,$0f
	.word @ref22
	.byte $ff,$07
	.word @ref23
@ref42:
	.byte $af,$2a,$cd
@ref43:
	.byte $f9,$85
	.byte $ff,$09
	.word @ref26
@ref44:
	.byte $f9,$85
	.byte $ff,$0a
	.word @ref28
	.byte $ff,$0b
	.word @ref29
	.byte $ff,$08
	.word @ref15
	.byte $ff,$07
	.word @ref16
@ref45:
	.byte $f9,$85
@ref46:
	.byte $df,$2c,$9b,$24
	.byte $ff,$05
	.word @ref19
	.byte $ff,$07
	.word @ref20
	.byte $ff,$07
	.word @ref21
	.byte $ff,$0f
	.word @ref22
	.byte $ff,$07
	.word @ref23
@ref47:
	.byte $af,$2a,$cd
@ref48:
	.byte $f9,$85
	.byte $ff,$09
	.word @ref26
@ref49:
	.byte $f9,$85
	.byte $ff,$0a
	.word @ref28
	.byte $ff,$0b
	.word @ref29
	.byte $ff,$08
	.word @ref15
	.byte $ff,$07
	.word @ref16
@ref50:
	.byte $f9,$85
@ref51:
	.byte $df,$2c,$9b,$24
	.byte $ff,$05
	.word @ref19
	.byte $ff,$07
	.word @ref20
	.byte $ff,$07
	.word @ref21
	.byte $ff,$0f
	.word @ref22
	.byte $ff,$07
	.word @ref23
@ref52:
	.byte $af,$2a,$cd
@ref53:
	.byte $f9,$85
	.byte $ff,$09
	.word @ref26
@ref54:
	.byte $f9,$85
	.byte $ff,$0a
	.word @ref28
	.byte $ff,$0b
	.word @ref29
	.byte $ff,$08
	.word @ref15
	.byte $ff,$07
	.word @ref16
@ref55:
	.byte $f9,$85
@ref56:
	.byte $df,$2c,$9b,$24
	.byte $ff,$05
	.word @ref19
	.byte $ff,$07
	.word @ref20
	.byte $ff,$07
	.word @ref21
@ref57:
	.byte $83,$30,$8b,$32,$8d,$30,$8b,$32,$cd
@ref58:
	.byte $f9,$85
@ref59:
	.byte $f9,$85
@ref60:
	.byte $f9,$85
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref61:
	.byte $f9,$85
@ref62:
	.byte $f9,$85
@ref63:
	.byte $f9,$85
@ref64:
	.byte $f9,$85
@ref65:
	.byte $f9,$85
@ref66:
	.byte $f9,$85
@ref67:
	.byte $f9,$85
@ref68:
	.byte $bf,$80,$06,$bd
@ref69:
	.byte $f9,$85
@ref70:
	.byte $af,$02,$cd
@ref71:
	.byte $f9,$85
@ref72:
	.byte $9f,$02,$dd
@ref73:
	.byte $f9,$85
@ref74:
	.byte $8f,$02,$e5,$02,$85
@ref75:
	.byte $f9,$85
@ref76:
	.byte $82,$1a,$84,$1a,$82,$1b,$80,$1b,$84,$1b,$82,$1b,$80,$1a,$00,$85,$40,$48,$4e,$40,$48,$4e,$40,$00,$8d,$82,$10,$84,$10,$82,$11,$80,$11,$84,$11,$82,$11,$80,$10,$00,$85,$40,$48,$4e,$40,$48,$4e,$40,$00,$8d,$82,$1a,$84,$1a,$82,$1a,$81
@ref77:
	.byte $80,$1b,$84,$1b,$82,$1b,$80,$1a,$00,$85,$40,$48,$4e,$40,$48,$4e,$40,$00,$8d,$82,$10,$84,$10,$82,$11,$80,$11,$84,$11,$82,$11,$80,$10,$00,$85,$40,$48,$4e,$00,$85,$40,$48,$4e,$40,$00,$85,$82,$12,$84,$12,$82,$13,$80,$13,$84,$12,$81
@ref78:
	.byte $82,$13,$80,$12,$00,$85,$42,$4a,$50,$42,$4a,$50,$42,$00,$8d,$82,$08,$84,$08,$82,$09,$80,$09,$84,$09,$82,$09,$80,$08,$00,$85,$42,$4a,$50,$42,$4a,$50,$42,$00,$8d,$82,$12,$84,$12,$82,$13,$80,$13,$84,$13,$82,$13,$80,$12,$00
@ref79:
	.byte $85,$42,$4a,$50,$42,$4a,$50,$42,$00,$8d,$82,$08,$84,$08,$82,$09,$80,$09,$84,$09,$82,$09,$80,$08,$00,$85,$42,$4a,$50,$00,$85,$42,$4a,$50,$42,$87,$82,$24,$84,$24,$82,$25,$80,$25,$84,$25,$82,$25,$80,$24,$00,$85,$3c
@ref80:
	.byte $44,$4a,$3c,$44,$4a,$3c,$00,$8d,$82,$1a,$84,$1a,$82,$1b,$80,$1b,$84,$1b,$82,$1b,$80,$1a,$00,$85,$3c,$44,$4a,$3c,$44,$4a,$3c,$00,$8d,$82,$24,$84,$24,$82,$25,$80,$25,$84,$25,$82,$25,$80,$24,$00,$85,$3c,$44,$4a,$3c,$44
@ref81:
	.byte $4a,$3c,$00,$8d,$82,$1a,$84,$1a,$82,$1b,$80,$1b,$84,$1b,$82,$1b,$80,$1a,$00,$85,$3c,$44,$4a,$00,$85,$3c,$44,$4a,$3c,$00,$85,$82,$24,$84,$24,$82,$25,$80,$25,$84,$25,$82,$25,$80,$24,$00,$85,$3c,$44,$4a,$3c,$44,$4a,$3c,$00,$81
@ref82:
	.byte $8b,$82,$1a,$84,$1a,$82,$1b,$80,$1b,$84,$1b,$82,$1b,$80,$1a,$00,$85,$3c,$44,$4a,$3c,$44,$4a,$3c,$00,$8d,$82,$24,$84,$24,$82,$25,$80,$25,$84,$25,$82,$25,$80,$24,$00,$85,$3c,$44,$4a,$3c,$44,$4a,$3c,$00,$89
@ref83:
	.byte $83,$82,$1a,$84,$1a,$82,$1b,$80,$1b,$84,$1b,$82,$1b,$80,$1a,$00,$85,$3c,$44,$4a,$00,$85,$3c,$44,$4a,$3c,$00,$85,$82,$1a,$84,$1a,$82,$1b,$80,$1b,$84,$1b,$82,$1b,$80,$1a,$00,$85,$40,$48,$4e,$40,$48,$4e,$40,$00,$8d,$82,$10,$84,$10
@ref84:
	.byte $82,$11,$80,$11,$84,$11,$82,$11,$80,$10,$00,$85,$40,$48,$4e,$40,$48,$4e,$40,$00,$8d,$82,$1a,$84,$1a,$82,$1b,$80,$1b,$84,$1b,$82,$1b,$80,$1a,$00,$85,$40,$48,$4e,$40,$48,$4e,$40,$00,$8d,$82,$10,$84,$10,$82,$11,$80,$10,$81
@ref85:
	.byte $84,$11,$82,$11,$80,$10,$00,$85,$40,$48,$4e,$00,$85,$40,$48,$4e,$40,$00,$85,$82,$12,$84,$12,$82,$13,$80,$13,$84,$13,$82,$13,$80,$12,$00,$85,$42,$4a,$50,$42,$4a,$50,$42,$00,$8d,$82,$08,$84,$08,$82,$09,$80,$09,$84,$09,$82,$08,$81
@ref86:
	.byte $80,$08,$00,$85,$42,$4a,$50,$42,$4a,$50,$42,$00,$8d,$82,$12,$84,$12,$82,$13,$80,$13,$84,$13,$82,$13,$80,$12,$00,$85,$42,$4a,$50,$42,$4a,$50,$42,$00,$8d,$82,$08,$84,$08,$82,$09,$80,$09,$84,$09,$82,$09,$80,$08,$00,$83
@ref87:
	.byte $81,$42,$4a,$50,$00,$85,$42,$4a,$50,$42,$87,$82,$24,$84,$24,$82,$25,$80,$25,$84,$25,$82,$25,$80,$24,$00,$85,$3c,$44,$4a,$3c,$44,$4a,$3c,$00,$8d,$82,$1a,$84,$1a,$82,$1b,$80,$1b,$84,$1b,$82,$1b,$80,$1a,$00,$85,$3c,$44,$4a
@ref88:
	.byte $3c,$44,$4a,$3c,$00,$8d,$82,$24,$84,$24,$82,$25,$80,$25,$84,$25,$82,$25,$80,$24,$00,$85,$3c,$44,$4a,$3c,$44,$4a,$3c,$00,$8d,$82,$1a,$84,$1a,$82,$1b,$80,$1b,$84,$1b,$82,$1b,$80,$1a,$00,$85,$3c,$44,$4a,$00,$85
@ref89:
	.byte $3c,$44,$4a,$3c,$00,$85,$82,$24,$84,$24,$82,$25,$80,$25,$84,$25,$82,$25,$80,$24,$00,$85,$3c,$44,$4a,$3c,$44,$4a,$3c,$00,$8d,$82,$1a,$84,$1a,$82,$1b,$80,$1b,$84,$1b,$82,$1b,$80,$1a,$00,$85,$3c,$44,$4a,$3c,$44,$4a,$3c,$00,$85
@ref90:
	.byte $87,$82,$24,$84,$24,$82,$25,$80,$25,$84,$25,$82,$25,$80,$24,$00,$85,$3c,$44,$4a,$3c,$44,$4a,$3c,$00,$8d,$82,$1a,$84,$1a,$82,$1b,$80,$1b,$84,$1b,$82,$1b,$80,$1a,$00,$85,$3c,$44,$4a,$00,$85,$3c,$44,$4a,$3c,$00,$85
	.byte $ff,$28
	.word @ref76
	.byte $ff,$29
	.word @ref77
	.byte $ff,$27
	.word @ref78
	.byte $ff,$27
	.word @ref79
	.byte $ff,$28
	.word @ref80
	.byte $ff,$2a
	.word @ref81
	.byte $ff,$25
	.word @ref82
	.byte $ff,$29
	.word @ref83
	.byte $ff,$27
	.word @ref84
	.byte $ff,$29
	.word @ref85
	.byte $ff,$27
	.word @ref86
	.byte $ff,$29
	.word @ref87
	.byte $ff,$26
	.word @ref88
	.byte $ff,$2a
	.word @ref89
	.byte $ff,$27
	.word @ref90
	.byte $ff,$28
	.word @ref76
	.byte $ff,$29
	.word @ref77
	.byte $ff,$27
	.word @ref78
	.byte $ff,$27
	.word @ref79
	.byte $ff,$28
	.word @ref80
	.byte $ff,$2a
	.word @ref81
	.byte $ff,$25
	.word @ref82
	.byte $ff,$29
	.word @ref83
	.byte $ff,$27
	.word @ref84
	.byte $ff,$29
	.word @ref85
	.byte $ff,$27
	.word @ref86
	.byte $ff,$29
	.word @ref87
	.byte $ff,$26
	.word @ref88
	.byte $ff,$2a
	.word @ref89
	.byte $ff,$27
	.word @ref90
	.byte $ff,$28
	.word @ref76
	.byte $ff,$29
	.word @ref77
	.byte $ff,$27
	.word @ref78
	.byte $ff,$27
	.word @ref79
	.byte $ff,$28
	.word @ref80
	.byte $ff,$2a
	.word @ref81
	.byte $ff,$25
	.word @ref82
	.byte $ff,$29
	.word @ref83
	.byte $ff,$27
	.word @ref84
	.byte $ff,$29
	.word @ref85
	.byte $ff,$27
	.word @ref86
	.byte $ff,$29
	.word @ref87
	.byte $ff,$26
	.word @ref88
	.byte $ff,$2a
	.word @ref89
	.byte $ff,$27
	.word @ref90
	.byte $ff,$28
	.word @ref76
	.byte $ff,$29
	.word @ref77
	.byte $ff,$27
	.word @ref78
	.byte $ff,$27
	.word @ref79
	.byte $ff,$28
	.word @ref80
	.byte $ff,$2a
	.word @ref81
	.byte $ff,$25
	.word @ref82
	.byte $ff,$29
	.word @ref83
	.byte $ff,$27
	.word @ref84
	.byte $ff,$29
	.word @ref85
	.byte $ff,$27
	.word @ref86
	.byte $ff,$29
	.word @ref87
	.byte $ff,$26
	.word @ref88
	.byte $ff,$2a
	.word @ref89
	.byte $ff,$27
	.word @ref90
	.byte $ff,$28
	.word @ref76
	.byte $ff,$29
	.word @ref77
	.byte $ff,$27
	.word @ref78
	.byte $ff,$27
	.word @ref79
	.byte $ff,$28
	.word @ref80
	.byte $ff,$2a
	.word @ref81
	.byte $ff,$25
	.word @ref82
	.byte $ff,$29
	.word @ref83
	.byte $ff,$27
	.word @ref84
	.byte $ff,$29
	.word @ref85
	.byte $ff,$27
	.word @ref86
	.byte $ff,$29
	.word @ref87
	.byte $ff,$26
	.word @ref88
	.byte $ff,$2a
	.word @ref89
	.byte $ff,$27
	.word @ref90
	.byte $ff,$28
	.word @ref76
	.byte $ff,$29
	.word @ref77
	.byte $ff,$27
	.word @ref78
	.byte $ff,$27
	.word @ref79
	.byte $ff,$28
	.word @ref80
	.byte $ff,$2a
	.word @ref81
	.byte $ff,$25
	.word @ref82
@ref91:
	.byte $83,$82,$1a,$84,$1a,$82,$1b,$80,$1b,$84,$1b,$82,$1b,$80,$1a,$00,$85,$3c,$44,$4a,$00,$85,$3c,$44,$4a,$3c,$00,$c5
@ref92:
	.byte $f9,$85
@ref93:
	.byte $f9,$85
@ref94:
	.byte $f9,$85
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref95:
	.byte $f9,$85
@ref96:
	.byte $f9,$85
@ref97:
	.byte $f9,$85
@ref98:
	.byte $f9,$85
@ref99:
	.byte $f9,$85
@ref100:
	.byte $f9,$85
@ref101:
	.byte $f9,$85
@ref102:
	.byte $f9,$85
@ref103:
	.byte $f9,$85
@ref104:
	.byte $f9,$85
@ref105:
	.byte $f9,$85
@ref106:
	.byte $f9,$85
@ref107:
	.byte $f9,$85
@ref108:
	.byte $f9,$85
@ref109:
	.byte $f9,$85
@ref110:
	.byte $80,$36,$26,$16,$32,$8d,$00,$a3,$36,$26,$16,$28,$8d,$00,$a3,$36,$26,$16,$32
@ref111:
	.byte $8d,$00,$a3,$36,$26,$16,$28,$8d,$00,$85,$36,$26,$16,$32,$8d,$00,$85,$36,$26,$16,$2a,$87
@ref112:
	.byte $85,$00,$a3,$36,$26,$16,$20,$8d,$00,$a3,$36,$26,$16,$2a,$8d,$00
@ref113:
	.byte $a3,$36,$26,$16,$20,$8d,$00,$85,$36,$26,$16,$2a,$8d,$00,$85,$36,$26,$16,$24,$8d,$00,$87
@ref114:
	.byte $9b,$36,$26,$16,$1a,$8d,$00,$a3,$36,$26,$16,$24,$8d,$00,$8f
@ref115:
	.byte $93,$36,$26,$16,$1a,$8d,$00,$85,$36,$26,$16,$24,$8d,$00,$85,$36,$26,$16,$24,$8d,$00,$97
@ref116:
	.byte $8b,$36,$26,$16,$1a,$8d,$00,$a3,$36,$26,$16,$24,$8d,$00,$9f
@ref117:
	.byte $83,$36,$26,$16,$1a,$8d,$00,$85,$36,$26,$16,$24,$8d,$00,$85,$36,$26,$16,$32,$8d,$00,$a3,$36,$26
@ref118:
	.byte $16,$28,$8d,$00,$a3,$36,$26,$16,$32,$8d,$00,$a3,$36,$26,$16,$28,$83
@ref119:
	.byte $89,$00,$85,$36,$26,$16,$32,$8d,$00,$85,$36,$26,$16,$2a,$8d,$00,$a3,$36,$26,$16,$20,$8b
@ref120:
	.byte $81,$00,$a3,$36,$26,$16,$2a,$8d,$00,$a3,$36,$26,$16,$20,$8d,$00,$83
@ref121:
	.byte $81,$36,$26,$16,$2a,$8d,$00,$85,$36,$26,$16,$24,$8d,$00,$a3,$36,$26,$16,$1a,$8d,$00,$8b
@ref122:
	.byte $97,$36,$26,$16,$24,$8d,$00,$a3,$36,$26,$16,$1a,$8d,$00,$85,$36,$26,$16,$24,$85
@ref123:
	.byte $87,$00,$85,$36,$26,$16,$24,$8d,$00,$a3,$36,$26,$16,$1a,$8d,$00,$9b
@ref124:
	.byte $87,$36,$26,$16,$24,$8d,$00,$a3,$36,$26,$16,$1a,$8d,$00,$85,$36,$26,$16,$24,$8d,$00,$85
@ref125:
	.byte $36,$26,$16,$32,$8d,$00,$a3,$36,$26,$16,$28,$8d,$00,$a3,$36,$26,$16,$32
	.byte $ff,$16
	.word @ref111
	.byte $ff,$10
	.word @ref112
	.byte $ff,$16
	.word @ref113
	.byte $ff,$0f
	.word @ref114
	.byte $ff,$16
	.word @ref115
	.byte $ff,$0f
	.word @ref116
	.byte $ff,$18
	.word @ref117
	.byte $ff,$11
	.word @ref118
	.byte $ff,$16
	.word @ref119
	.byte $ff,$11
	.word @ref120
	.byte $ff,$16
	.word @ref121
	.byte $ff,$14
	.word @ref122
	.byte $ff,$11
	.word @ref123
	.byte $ff,$16
	.word @ref124
	.byte $ff,$12
	.word @ref125
	.byte $ff,$16
	.word @ref111
	.byte $ff,$10
	.word @ref112
	.byte $ff,$16
	.word @ref113
	.byte $ff,$0f
	.word @ref114
	.byte $ff,$16
	.word @ref115
	.byte $ff,$0f
	.word @ref116
	.byte $ff,$18
	.word @ref117
	.byte $ff,$11
	.word @ref118
	.byte $ff,$16
	.word @ref119
	.byte $ff,$11
	.word @ref120
	.byte $ff,$16
	.word @ref121
	.byte $ff,$14
	.word @ref122
	.byte $ff,$11
	.word @ref123
	.byte $ff,$16
	.word @ref124
	.byte $ff,$12
	.word @ref125
	.byte $ff,$16
	.word @ref111
	.byte $ff,$10
	.word @ref112
	.byte $ff,$16
	.word @ref113
	.byte $ff,$0f
	.word @ref114
	.byte $ff,$16
	.word @ref115
	.byte $ff,$0f
	.word @ref116
	.byte $ff,$18
	.word @ref117
	.byte $ff,$11
	.word @ref118
	.byte $ff,$16
	.word @ref119
	.byte $ff,$11
	.word @ref120
	.byte $ff,$16
	.word @ref121
	.byte $ff,$14
	.word @ref122
	.byte $ff,$11
	.word @ref123
	.byte $ff,$16
	.word @ref124
	.byte $ff,$12
	.word @ref125
	.byte $ff,$16
	.word @ref111
	.byte $ff,$10
	.word @ref112
	.byte $ff,$16
	.word @ref113
	.byte $ff,$0f
	.word @ref114
	.byte $ff,$16
	.word @ref115
	.byte $ff,$0f
	.word @ref116
	.byte $ff,$18
	.word @ref117
	.byte $ff,$11
	.word @ref118
	.byte $ff,$16
	.word @ref119
	.byte $ff,$11
	.word @ref120
	.byte $ff,$16
	.word @ref121
	.byte $ff,$14
	.word @ref122
	.byte $ff,$11
	.word @ref123
	.byte $ff,$16
	.word @ref124
	.byte $ff,$12
	.word @ref125
	.byte $ff,$16
	.word @ref111
	.byte $ff,$10
	.word @ref112
	.byte $ff,$16
	.word @ref113
	.byte $ff,$0f
	.word @ref114
	.byte $ff,$16
	.word @ref115
	.byte $ff,$0f
	.word @ref116
	.byte $ff,$18
	.word @ref117
	.byte $ff,$11
	.word @ref118
	.byte $ff,$16
	.word @ref119
	.byte $ff,$11
	.word @ref120
	.byte $ff,$16
	.word @ref121
	.byte $ff,$14
	.word @ref122
	.byte $ff,$11
	.word @ref123
	.byte $ff,$16
	.word @ref124
	.byte $ff,$12
	.word @ref125
	.byte $ff,$16
	.word @ref111
	.byte $ff,$10
	.word @ref112
	.byte $ff,$16
	.word @ref113
	.byte $ff,$0f
	.word @ref114
	.byte $ff,$16
	.word @ref115
	.byte $ff,$0f
	.word @ref116
@ref126:
	.byte $83,$36,$26,$16,$1a,$8d,$00,$85,$36,$26,$16,$24,$8d,$00,$c5
@ref127:
	.byte $f9,$85
@ref128:
	.byte $f9,$85
@ref129:
	.byte $f9,$85
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref130:
	.byte $f9,$85
@ref131:
	.byte $f9,$85
@ref132:
	.byte $f9,$85
@ref133:
	.byte $f9,$85
@ref134:
	.byte $f9,$85
@ref135:
	.byte $f9,$85
@ref136:
	.byte $f9,$85
@ref137:
	.byte $f9,$85
@ref138:
	.byte $f9,$85
@ref139:
	.byte $f9,$85
@ref140:
	.byte $f9,$85
@ref141:
	.byte $9f,$80,$54,$56,$5c,$42,$00,$93,$54,$56,$5c,$42,$00,$83,$54,$56,$5c,$42,$00,$85,$42,$52,$56,$58,$56,$58,$5b,$00,$8b,$54,$56,$5c
@ref142:
	.byte $42,$00,$83,$54,$56,$5c,$42,$00,$85,$54,$56,$5c,$42,$00,$93,$54,$56,$5c,$42,$00,$83,$54,$56,$5c,$42,$00,$85,$42,$52,$56,$58,$56,$58,$5b,$00,$8b,$54,$56,$5c,$42,$00,$83
@ref143:
	.byte $54,$56,$5c,$42,$00,$85,$54,$56,$5c,$42,$00,$93,$54,$56,$5c,$42,$00,$83,$54,$56,$5c,$42,$00,$85,$42,$52,$56,$58,$56,$58,$5b,$00,$8b,$54,$56,$5c,$42,$00,$83,$54,$56,$5c,$42
@ref144:
	.byte $00,$85,$42,$52,$56,$58,$56,$58,$5a,$42,$52,$56,$58,$56,$58,$5b,$42,$52,$56,$58,$56,$58,$5a,$42,$52,$56,$58,$56,$58,$5b,$42,$52,$56,$58,$56,$58,$5a,$42,$52,$56,$58,$56,$58,$5b,$42,$52,$56,$58,$56,$58,$5a,$42,$52,$56,$58,$56,$58,$5a,$81
@ref145:
	.byte $54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5b,$00,$8b,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5b,$00,$8b,$54,$56,$5c,$42
@ref146:
	.byte $00,$93,$42,$52,$56,$58,$56,$58,$5b,$00,$8b,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5a,$42,$52,$56,$58,$56,$58,$5b,$54,$56,$5c,$42,$00,$85
@ref147:
	.byte $8d,$42,$52,$56,$58,$56,$58,$5b,$00,$8b,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5b,$00,$8b,$54,$56,$5c,$42,$00,$8d
@ref148:
	.byte $85,$42,$52,$56,$58,$56,$58,$5b,$00,$8b,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5a,$42,$52,$56,$58,$56,$58,$5b,$54,$56,$5c,$42,$00,$93,$42
@ref149:
	.byte $52,$56,$58,$56,$58,$5b,$00,$8b,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5b,$00,$8b,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56
@ref150:
	.byte $58,$5b,$00,$8b,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5a,$42,$52,$56,$58,$56,$58,$5b,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5b,$00
@ref151:
	.byte $8b,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5b,$00,$8b,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5b,$00,$87
@ref152:
	.byte $83,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5a,$42,$52,$56,$58,$56,$58,$5b,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5b,$00,$8b,$54,$56
@ref153:
	.byte $5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5b,$00,$8b,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5b,$00,$8b,$54,$56,$5c,$42,$00,$81
@ref154:
	.byte $91,$42,$52,$56,$58,$56,$58,$5a,$42,$52,$56,$58,$56,$58,$5b,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5b,$00,$8b,$54,$56,$5c,$42,$00,$89
@ref155:
	.byte $89,$42,$52,$56,$58,$56,$58,$5b,$00,$8b,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5b,$00,$8b,$54,$56,$5c,$42,$00,$91
@ref156:
	.byte $81,$42,$52,$56,$58,$56,$58,$5a,$42,$52,$56,$58,$56,$58,$5b,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5b,$00,$8b,$54,$56,$5c,$42,$00,$93,$42,$52,$56
@ref157:
	.byte $58,$56,$58,$5b,$00,$8b,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5b,$00,$8b,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5a
@ref158:
	.byte $42,$52,$56,$58,$56,$58,$5b,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5b,$00,$8b,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5b,$00,$83
@ref159:
	.byte $87,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5b,$00,$8b,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5a,$42,$52,$56,$58,$56,$58,$5a,$81
	.byte $ff,$22
	.word @ref145
	.byte $ff,$25
	.word @ref146
	.byte $ff,$1f
	.word @ref147
	.byte $ff,$25
	.word @ref148
	.byte $ff,$22
	.word @ref149
	.byte $ff,$26
	.word @ref150
	.byte $ff,$1f
	.word @ref151
	.byte $ff,$26
	.word @ref152
	.byte $ff,$22
	.word @ref153
	.byte $ff,$24
	.word @ref154
	.byte $ff,$1f
	.word @ref155
	.byte $ff,$27
	.word @ref156
	.byte $ff,$22
	.word @ref157
	.byte $ff,$25
	.word @ref158
	.byte $ff,$25
	.word @ref159
	.byte $ff,$22
	.word @ref145
	.byte $ff,$25
	.word @ref146
	.byte $ff,$1f
	.word @ref147
	.byte $ff,$25
	.word @ref148
	.byte $ff,$22
	.word @ref149
	.byte $ff,$26
	.word @ref150
	.byte $ff,$1f
	.word @ref151
	.byte $ff,$26
	.word @ref152
	.byte $ff,$22
	.word @ref153
	.byte $ff,$24
	.word @ref154
	.byte $ff,$1f
	.word @ref155
	.byte $ff,$27
	.word @ref156
	.byte $ff,$22
	.word @ref157
	.byte $ff,$25
	.word @ref158
	.byte $ff,$25
	.word @ref159
	.byte $ff,$22
	.word @ref145
	.byte $ff,$25
	.word @ref146
	.byte $ff,$1f
	.word @ref147
	.byte $ff,$25
	.word @ref148
	.byte $ff,$22
	.word @ref149
	.byte $ff,$26
	.word @ref150
	.byte $ff,$1f
	.word @ref151
	.byte $ff,$26
	.word @ref152
	.byte $ff,$22
	.word @ref153
	.byte $ff,$24
	.word @ref154
	.byte $ff,$1f
	.word @ref155
	.byte $ff,$27
	.word @ref156
	.byte $ff,$22
	.word @ref157
	.byte $ff,$25
	.word @ref158
	.byte $ff,$25
	.word @ref159
	.byte $ff,$22
	.word @ref145
	.byte $ff,$25
	.word @ref146
	.byte $ff,$1f
	.word @ref147
	.byte $ff,$25
	.word @ref148
	.byte $ff,$22
	.word @ref149
	.byte $ff,$26
	.word @ref150
	.byte $ff,$1f
	.word @ref151
	.byte $ff,$26
	.word @ref152
	.byte $ff,$22
	.word @ref153
	.byte $ff,$24
	.word @ref154
	.byte $ff,$1f
	.word @ref155
	.byte $ff,$27
	.word @ref156
	.byte $ff,$22
	.word @ref157
	.byte $ff,$25
	.word @ref158
	.byte $ff,$25
	.word @ref159
	.byte $ff,$22
	.word @ref145
	.byte $ff,$25
	.word @ref146
	.byte $ff,$1f
	.word @ref147
	.byte $ff,$25
	.word @ref148
	.byte $ff,$22
	.word @ref149
	.byte $ff,$26
	.word @ref150
	.byte $ff,$1f
	.word @ref151
	.byte $ff,$26
	.word @ref152
	.byte $ff,$22
	.word @ref153
	.byte $ff,$24
	.word @ref154
	.byte $ff,$1f
	.word @ref155
	.byte $ff,$27
	.word @ref156
	.byte $ff,$22
	.word @ref157
	.byte $ff,$25
	.word @ref158
	.byte $ff,$25
	.word @ref159
	.byte $ff,$22
	.word @ref145
	.byte $ff,$25
	.word @ref146
	.byte $ff,$1f
	.word @ref147
	.byte $ff,$25
	.word @ref148
	.byte $ff,$22
	.word @ref149
	.byte $ff,$26
	.word @ref150
	.byte $ff,$1f
	.word @ref151
@ref160:
	.byte $83,$54,$56,$5c,$42,$00,$93,$42,$52,$56,$58,$56,$58,$5a,$42,$52,$56,$58,$56,$58,$5a,$c1
@ref161:
	.byte $f9,$85
@ref162:
	.byte $f9,$85
@ref163:
	.byte $f9,$85
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref164:
	.byte $f9,$85
@ref165:
	.byte $f9,$85
@ref166:
	.byte $f9,$85
@ref167:
	.byte $f9,$85
@ref168:
	.byte $f9,$85
@ref169:
	.byte $f9,$85
@ref170:
	.byte $f9,$85
@ref171:
	.byte $f9,$85
@ref172:
	.byte $f9,$85
@ref173:
	.byte $f9,$85
@ref174:
	.byte $f9,$85
@ref175:
	.byte $f9,$85
@ref176:
	.byte $f9,$85
@ref177:
	.byte $f9,$85
@ref178:
	.byte $f9,$85
@ref179:
	.byte $f9,$85
@ref180:
	.byte $f9,$85
@ref181:
	.byte $f9,$85
@ref182:
	.byte $f9,$85
@ref183:
	.byte $f9,$85
@ref184:
	.byte $f9,$85
@ref185:
	.byte $f9,$85
@ref186:
	.byte $f9,$85
@ref187:
	.byte $f9,$85
@ref188:
	.byte $f9,$85
@ref189:
	.byte $f9,$85
@ref190:
	.byte $f9,$85
@ref191:
	.byte $f9,$85
@ref192:
	.byte $f9,$85
@ref193:
	.byte $f9,$85
@ref194:
	.byte $f9,$85
@ref195:
	.byte $f9,$85
@ref196:
	.byte $f9,$85
@ref197:
	.byte $f9,$85
@ref198:
	.byte $f9,$85
@ref199:
	.byte $f9,$85
@ref200:
	.byte $f9,$85
@ref201:
	.byte $f9,$85
@ref202:
	.byte $f9,$85
@ref203:
	.byte $f9,$85
@ref204:
	.byte $f9,$85
@ref205:
	.byte $f9,$85
@ref206:
	.byte $f9,$85
@ref207:
	.byte $f9,$85
@ref208:
	.byte $f9,$85
@ref209:
	.byte $f9,$85
@ref210:
	.byte $f9,$85
@ref211:
	.byte $f9,$85
@ref212:
	.byte $f9,$85
@ref213:
	.byte $f9,$85
@ref214:
	.byte $f9,$85
@ref215:
	.byte $f9,$85
@ref216:
	.byte $f9,$85
@ref217:
	.byte $f9,$85
@ref218:
	.byte $f9,$85
@ref219:
	.byte $f9,$85
@ref220:
	.byte $f9,$85
@ref221:
	.byte $f9,$85
@ref222:
	.byte $f9,$85
@ref223:
	.byte $f9,$85
@ref224:
	.byte $f9,$85
@ref225:
	.byte $f9,$85
@ref226:
	.byte $f9,$85
@ref227:
	.byte $f9,$85
@ref228:
	.byte $f9,$85
@ref229:
	.byte $f9,$85
@ref230:
	.byte $f9,$85
@ref231:
	.byte $f9,$85
@ref232:
	.byte $f9,$85
@ref233:
	.byte $f9,$85
@ref234:
	.byte $f9,$85
@ref235:
	.byte $f9,$85
@ref236:
	.byte $f9,$85
@ref237:
	.byte $f9,$85
@ref238:
	.byte $f9,$85
@ref239:
	.byte $f9,$85
@ref240:
	.byte $f9,$85
@ref241:
	.byte $f9,$85
@ref242:
	.byte $f9,$85
@ref243:
	.byte $f9,$85
@ref244:
	.byte $f9,$85
@ref245:
	.byte $f9,$85
@ref246:
	.byte $f9,$85
@ref247:
	.byte $f9,$85
@ref248:
	.byte $f9,$85
@ref249:
	.byte $f9,$85
@ref250:
	.byte $f9,$85
@ref251:
	.byte $f9,$85
@ref252:
	.byte $f9,$85
@ref253:
	.byte $f9,$85
@ref254:
	.byte $f9,$85
@ref255:
	.byte $f9,$85
@ref256:
	.byte $f9,$85
@ref257:
	.byte $f9,$85
@ref258:
	.byte $f9,$85
@ref259:
	.byte $f9,$85
@ref260:
	.byte $f9,$85
@ref261:
	.byte $f9,$85
@ref262:
	.byte $f9,$85
@ref263:
	.byte $f9,$85
@ref264:
	.byte $f9,$85
@ref265:
	.byte $f9,$85
@ref266:
	.byte $f9,$85
@ref267:
	.byte $f9,$85
@ref268:
	.byte $f9,$85
@ref269:
	.byte $f9,$85
@ref270:
	.byte $f9,$85
@ref271:
	.byte $f9,$85
@ref272:
	.byte $f9,$85
@ref273:
	.byte $f9,$85
@ref274:
	.byte $f9,$85
@ref275:
	.byte $f9,$85
@ref276:
	.byte $f9,$85
@ref277:
	.byte $f9,$85
@ref278:
	.byte $f9,$85
@ref279:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop
