;this file for FamiTone2 library generated by FamiStudio
FT_DPCM_PTR=$c000
  .export _my_lost_soul_danmaku_music_data
_my_lost_soul_danmaku_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256




@instruments:
	.byte $30 ;instrument 00 (Duty 0)
	.word @env1, @env0, @env0
	.byte $00
	.byte $70 ;instrument 01 (Duty 1)
	.word @env1, @env0, @env0
	.byte $00

@samples:
@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $cf,$7f,$00,$00

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
@ref0:
	.byte $82,$4a,$cb,$46,$cb,$44,$e3,$40,$b1,$3c,$c9,$3a,$cb,$36,$ad
@ref1:
	.byte $f9,$bd,$00,$af,$36,$a5,$3a,$a3,$3c,$c9,$44,$cb,$3a,$ab
@ref2:
	.byte $9f,$44,$c9,$36,$cb,$3c,$a3,$3a,$a3,$32,$a5,$2c,$a3,$32,$a3,$4a,$a3,$4e,$dd
@ref3:
	.byte $bb,$4a,$c9,$44,$cb,$40,$a3,$3c,$a3,$40,$a5,$3c,$a3,$44,$f1,$4a,$99
@ref4:
	.byte $89,$4e,$f9,$9d,$4a,$cb,$44,$c9,$40,$a5,$3c,$a3,$40,$a3,$3c,$a3,$44,$a5
@ref5:
	.byte $a5,$36,$a3,$3a,$a5,$3c,$c9,$44,$cb,$3a,$c9,$44,$cb,$36,$d5
@ref6:
	.byte $f9,$f9,$f9,$8d,$00,$ab,$4e,$d3
@ref7:
	.byte $c7,$00,$cf,$4a,$f5,$54,$f5,$4e,$f3
@ref8:
	.byte $9f,$52,$9b,$54,$b9,$52,$d7,$4e,$d7,$52,$b9,$54,$f9,$99
@ref9:
	.byte $87,$00,$c5,$56,$87,$58,$d7,$54,$d7,$58,$b9,$5c,$f5,$58,$bb
@ref10:
	.byte $af,$52,$87,$54,$a9,$52,$ab,$4a,$9b,$4e,$a9,$46,$ab,$4c,$9b,$4e,$f9,$a1,$00,$b5
@ref11:
	.byte $99,$4a,$f5,$54,$f5,$4e,$f9,$99,$52,$9b,$54,$b9,$52,$83
@ref12:
	.byte $d3,$4e,$d7,$52,$b9,$54,$f9,$a1,$00,$c5,$56,$87,$58,$a3
@ref13:
	.byte $b3,$54,$d7,$58,$b9,$5c,$f5,$58,$eb,$52,$87,$54,$a9,$52,$97
@ref14:
	.byte $93,$4a,$9b,$4e,$a9,$46,$ab,$4c,$9b,$4e,$f9,$9d,$4a,$cb,$44,$c9,$40,$9f
@ref15:
	.byte $85,$3c,$a3,$40,$a3,$3c,$a3,$44,$cb,$36,$a3,$3a,$a5,$3c,$c9,$44,$cb,$3a,$c9,$44,$83
@ref16:
	.byte $c7,$36,$f9,$f9,$f9,$c7
@ref17:
	.byte $9b,$00,$ab,$4a,$cb,$46,$c9,$44,$e5,$40,$af,$3c,$cb,$3a,$b1
@ref18:
	.byte $97,$36,$f9,$ed,$00,$af,$36,$a3,$3a,$a3,$3c,$cb,$44,$af
@ref19:
	.byte $9b,$3a,$c9,$44,$cb,$36,$c9,$3c,$a5,$3a,$a3,$32,$a3,$2c,$a3,$32,$a5,$4a,$a3,$4e,$93
@ref20:
	.byte $f9,$89,$4a,$cb,$44,$c9,$40,$a5,$3c,$a3,$40,$a3,$3c,$a3,$44,$c5
@ref21:
	.byte $ab,$4a,$a5,$4e,$f9,$9d,$4a,$c9,$44,$cb,$40,$a3,$3c,$a3,$40,$a5,$3c,$81
@ref22:
	.byte $a1,$44,$cb,$36,$a3,$3a,$a3,$3c,$cb,$44,$c9,$3a,$cb,$44,$c9,$36,$8d
@ref23:
	.byte $f9,$f9,$f9,$d3,$00,$af,$4e,$89
@ref24:
	.byte $f9,$97,$00,$cd,$4a,$f5,$54,$f5,$4e,$ab
@ref25:
	.byte $e7,$52,$9b,$54,$b9,$52,$d7,$4e,$d7,$52,$b9,$54,$cb
@ref26:
	.byte $cf,$00,$c7,$56,$85,$58,$d7,$54,$d7,$58,$b9,$5c,$eb
@ref27:
	.byte $89,$58,$ed,$52,$85,$54,$ab,$52,$a9,$4a,$9b,$4e,$ab,$46,$a9,$4c,$9b,$4e,$f9,$91
@ref28:
	.byte $8f,$00,$f9,$f9,$f9,$f9,$85
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref29:
	.byte $82,$40,$cb,$3c,$cb,$36,$f9,$9d,$34,$f9,$9d,$2c,$ad
@ref30:
	.byte $f9,$bd,$00,$f9,$83,$36,$f9,$9d,$34,$ab
@ref31:
	.byte $eb,$2c,$f9,$f9,$bd,$46,$dd
@ref32:
	.byte $bb,$44,$c9,$3c,$f9,$eb,$3a,$f9,$93
@ref33:
	.byte $89,$46,$f9,$9d,$44,$cb,$3c,$f9,$e9,$3a,$a5
@ref34:
	.byte $f3,$36,$f9,$9d,$34,$f9,$9d,$2c,$d5
@ref35:
	.byte $f9,$f9,$f9,$8d,$00,$ab,$44,$d3
@ref36:
	.byte $c7,$00,$cf,$40,$f5,$4a,$f5,$44,$f3
@ref37:
	.byte $81,$46,$9b,$4a,$9b,$4e,$b9,$4c,$d7,$46,$d7,$4a,$f9,$d5
@ref38:
	.byte $87,$00,$cf,$4e,$d7,$4a,$d7,$4e,$b9,$52,$f5,$4e,$bb
@ref39:
	.byte $b9,$4c,$d7,$40,$9b,$44,$a9,$3c,$ab,$40,$9b,$44,$f9,$a1,$00,$b5
@ref40:
	.byte $99,$40,$f5,$4a,$f5,$44,$f5,$46,$9b,$4a,$9b,$4e,$b9,$4c,$83
@ref41:
	.byte $d3,$46,$d7,$4a,$f9,$dd,$00,$cf,$4e,$a3
@ref42:
	.byte $b3,$4a,$d7,$4e,$b9,$52,$f5,$4e,$f5,$4c,$c3
@ref43:
	.byte $93,$40,$9b,$44,$a9,$3c,$ab,$40,$9b,$46,$f9,$9d,$44,$cb,$3c,$eb
@ref44:
	.byte $f7,$3a,$f9,$9f,$36,$f9,$9d,$34,$cf
@ref45:
	.byte $c7,$2c,$f9,$f9,$f9,$c7
@ref46:
	.byte $9b,$00,$ab,$40,$cb,$3c,$c9,$36,$f9,$9d,$34,$f9,$85
@ref47:
	.byte $97,$2c,$f9,$ed,$00,$f9,$81,$36,$f9,$83
@ref48:
	.byte $9b,$34,$f9,$9d,$2c,$f9,$f9,$bd,$46,$93
@ref49:
	.byte $f9,$89,$44,$cb,$3c,$f9,$e9,$3a,$c5
@ref50:
	.byte $d3,$46,$f9,$9d,$44,$c9,$3c,$f9,$c9
@ref51:
	.byte $a1,$3a,$f9,$9d,$36,$f9,$9d,$34,$f9,$9d,$2c,$8d
@ref52:
	.byte $f9,$f9,$f9,$d3,$00,$af,$44,$89
@ref53:
	.byte $f9,$97,$00,$cd,$40,$f5,$4a,$f5,$44,$ab
@ref54:
	.byte $c9,$46,$9b,$4a,$9b,$4e,$b9,$4c,$d7,$46,$d7,$4a,$f9,$8d
@ref55:
	.byte $cf,$00,$cf,$4e,$d7,$4a,$d7,$4e,$b9,$52,$eb
@ref56:
	.byte $89,$4e,$f5,$4c,$d7,$40,$9b,$44,$ab,$3c,$a9,$40,$9b,$44,$f9,$91
	.byte $ff,$07
	.word @ref28
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref57:
	.byte $f9,$a1,$80,$1e,$f9,$9d,$1c,$f9,$9d,$1e,$ad
@ref58:
	.byte $e9,$00,$f9,$d1,$1e,$f9,$9d,$1c,$ab
@ref59:
	.byte $eb,$1e,$f9,$f9,$bd,$2e,$dd
@ref60:
	.byte $bb,$32,$f9,$9d,$28,$f9,$9d,$22,$f9,$93
@ref61:
	.byte $89,$2e,$f9,$9d,$32,$f9,$9d,$28,$f9,$9d,$22,$a5
@ref62:
	.byte $f3,$1e,$f9,$9d,$1c,$f9,$9d,$1e,$d5
@ref63:
	.byte $c1,$00,$f9,$f9,$f1,$2c,$d3
@ref64:
	.byte $f9,$9f,$28,$f9,$f3,$24,$f3
@ref65:
	.byte $f9,$28,$f9,$f3,$2c,$f9,$99
@ref66:
	.byte $d9,$28,$f9,$f3,$24,$f9,$b9
@ref67:
	.byte $b9,$22,$f9,$f3,$2c,$f9,$d9
@ref68:
	.byte $99,$28,$f9,$f3,$24,$f9,$f3,$28,$83
@ref69:
	.byte $f9,$ef,$2c,$f9,$f3,$28,$a3
@ref70:
	.byte $f9,$cf,$24,$f9,$f3,$22,$c3
@ref71:
	.byte $f9,$af,$2e,$f9,$9d,$32,$f9,$9d,$28,$9f
@ref72:
	.byte $f7,$22,$f9,$9f,$1e,$f9,$9d,$1c,$cf
@ref73:
	.byte $c7,$1e,$f9,$9d,$00,$f9,$f9,$a7
@ref74:
	.byte $f9,$e9,$1e,$f9,$9d,$1c,$f9,$85
@ref75:
	.byte $97,$1e,$f9,$9f,$00,$f9,$cf,$1e,$f9,$83
@ref76:
	.byte $9b,$1c,$f9,$9d,$1e,$f9,$f9,$bd,$2e,$93
@ref77:
	.byte $f9,$89,$32,$f9,$9d,$28,$f9,$9d,$22,$c5
@ref78:
	.byte $d3,$2e,$f9,$9d,$32,$f9,$9d,$28,$f5
@ref79:
	.byte $a1,$22,$f9,$9d,$1e,$f9,$9d,$1c,$f9,$9d,$1e,$8d
@ref80:
	.byte $f9,$91,$00,$f9,$f9,$f1,$2c,$89
@ref81:
	.byte $f9,$e7,$28,$f9,$f3,$24,$ab
@ref82:
	.byte $f9,$c7,$28,$f9,$f3,$2c,$cb
@ref83:
	.byte $f9,$a7,$28,$f9,$f3,$24,$eb
@ref84:
	.byte $f9,$87,$22,$f9,$f3,$2c,$f9,$91
@ref85:
	.byte $f9,$f9,$f9,$f9,$97
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $ff,$05
	.word @ref85
	.byte $fd
	.word @song0ch4loop
