;this file for FamiTone2 library generated by FamiStudio
FT_DPCM_PTR=$c000
 .export _rickroll_music_data
_rickroll_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256




@instruments:
	.byte $b0 ;instrument 00 (Choir Clone)
	.word @env1, @env0, @env0
	.byte $00
	.byte $30 ;instrument 01 (Chord 1)
	.word @env6, @env0, @env0
	.byte $00
	.byte $30 ;instrument 02 (Hi Hat)
	.word @env2, @env0, @env0
	.byte $00
	.byte $30 ;instrument 03 (Noise Snare)
	.word @env5, @env0, @env0
	.byte $00
	.byte $30 ;instrument 04 (Tri Kick)
	.word @env7, @env0, @env3
	.byte $00
	.byte $30 ;instrument 05 (Tri lead)
	.word @env4, @env0, @env0
	.byte $00
	.byte $30 ;instrument 06 (Tri Lead 2)
	.word @env4, @env0, @env0
	.byte $00

@samples:
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;1 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;2 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;3 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;4 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;5 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;6 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;7 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;8 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;9 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;10 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;11 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;12 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;13 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;14 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;15 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;16 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;17 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;18 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;19 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;20 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;21 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;22 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;23 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;24 
	.byte $00+.lobyte(FT_DPCM_PTR),$08,$0f	;25 (BuckyOHare_$FF40.dmc)
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;26 
	.byte $03+.lobyte(FT_DPCM_PTR),$20,$0f	;27 (AkumajouDensetsu_$C040.dmc)
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;28 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;29 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;30 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;31 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;32 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;33 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;34 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;35 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;36 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;37 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;38 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;39 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;40 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;41 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;42 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;43 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;44 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;45 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;46 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;47 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;48 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;49 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;50 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;51 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;52 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;53 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;54 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;55 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;56 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;57 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;58 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;59 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;60 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;61 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;62 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;63 

@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $c8,$c7,$07,$c6,$c6,$00,$04
@env2:
	.byte $c8,$c3,$c1,$c0,$00,$03
@env3:
	.byte $f2,$00,$00
@env4:
	.byte $cf,$7f,$00,$00
@env5:
	.byte $cb,$c8,$c6,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$0b
@env6:
	.byte $c6,$c6,$c5,$08,$c4,$0a,$c3,$c3,$00,$07
@env7:
	.byte $cf,$06,$c0,$00,$02

@song0ch0:
@ref0:
	.byte $00,$bd
@ref1:
	.byte $82,$22,$95,$26,$a5,$26,$95,$2a,$a5
@ref2:
	.byte $22,$95,$26,$a5,$26,$95,$2a,$a5
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref2
@ref3:
	.byte $22,$bd,$26,$bd
@ref4:
	.byte $22,$bd,$22,$95,$26,$a5
@ref5:
	.byte $22,$bd,$26,$bd
	.byte $ff,$06
	.word @ref4
@ref6:
	.byte $3a,$b5,$3e,$bd,$42,$85
@ref7:
	.byte $bf,$3a,$89,$3a,$89,$3e,$95,$26,$8d
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref2
@ref8:
	.byte $22,$bd,$26,$bd
	.byte $ff,$06
	.word @ref4
@ref9:
	.byte $22,$bd,$26,$bd
	.byte $ff,$06
	.word @ref4
	.byte $ff,$06
	.word @ref6
	.byte $ff,$09
	.word @ref7
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref2
@ref10:
	.byte $00,$bd,$80,$38,$89,$38,$89,$34,$a5
@ref11:
	.byte $00,$bd,$38,$89,$38,$89,$34,$a5
	.byte $ff,$08
	.word @ref11
	.byte $ff,$08
	.word @ref11
	.byte $ff,$08
	.word @ref11
	.byte $ff,$08
	.word @ref11
	.byte $ff,$08
	.word @ref11
	.byte $ff,$08
	.word @ref11
@ref12:
	.byte $00,$f9,$83
@ref13:
	.byte $00,$bd,$22,$95,$20,$a5
@ref14:
	.byte $00,$f9,$83
	.byte $ff,$06
	.word @ref13
@ref15:
	.byte $82,$3a,$b5,$3e,$bd,$42,$85
	.byte $ff,$09
	.word @ref7
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref10
	.byte $ff,$08
	.word @ref11
	.byte $ff,$08
	.word @ref11
	.byte $ff,$08
	.word @ref11
	.byte $ff,$08
	.word @ref11
	.byte $ff,$08
	.word @ref11
@song0ch0loop:
	.byte $00
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@ref16:
	.byte $00,$bd
@ref17:
	.byte $82,$2a,$95,$2e,$a5,$2e,$95,$30,$a5
@ref18:
	.byte $2a,$95,$2e,$a5,$2e,$95,$30,$a5
	.byte $ff,$08
	.word @ref18
	.byte $ff,$08
	.word @ref18
@ref19:
	.byte $30,$bd,$2e,$bd
@ref20:
	.byte $30,$bd,$30,$95,$2e,$a5
@ref21:
	.byte $30,$bd,$2e,$bd
	.byte $ff,$06
	.word @ref20
@ref22:
	.byte $42,$b5,$46,$bd,$48,$85
@ref23:
	.byte $bf,$42,$89,$42,$89,$46,$95,$34,$8d
	.byte $ff,$08
	.word @ref18
	.byte $ff,$08
	.word @ref18
	.byte $ff,$08
	.word @ref18
	.byte $ff,$08
	.word @ref18
@ref24:
	.byte $30,$bd,$2e,$bd
	.byte $ff,$06
	.word @ref20
@ref25:
	.byte $30,$bd,$2e,$bd
	.byte $ff,$06
	.word @ref20
	.byte $ff,$06
	.word @ref22
	.byte $ff,$09
	.word @ref23
	.byte $ff,$08
	.word @ref18
	.byte $ff,$08
	.word @ref18
	.byte $ff,$08
	.word @ref18
	.byte $ff,$08
	.word @ref18
	.byte $ff,$08
	.word @ref18
	.byte $ff,$08
	.word @ref18
	.byte $ff,$08
	.word @ref18
	.byte $ff,$08
	.word @ref18
@ref26:
	.byte $00,$bd,$80,$3e,$89,$3e,$89,$3e,$a5
@ref27:
	.byte $00,$bd,$3e,$89,$3e,$89,$3e,$a5
	.byte $ff,$08
	.word @ref27
	.byte $ff,$08
	.word @ref27
	.byte $ff,$08
	.word @ref27
	.byte $ff,$08
	.word @ref27
	.byte $ff,$08
	.word @ref27
	.byte $ff,$08
	.word @ref27
@ref28:
	.byte $00,$f9,$83
@ref29:
	.byte $00,$bd,$30,$95,$2e,$a5
@ref30:
	.byte $00,$f9,$83
	.byte $ff,$06
	.word @ref29
@ref31:
	.byte $82,$42,$b5,$46,$bd,$48,$85
	.byte $ff,$09
	.word @ref23
	.byte $ff,$08
	.word @ref18
	.byte $ff,$08
	.word @ref18
	.byte $ff,$08
	.word @ref18
	.byte $ff,$08
	.word @ref18
	.byte $ff,$08
	.word @ref18
	.byte $ff,$08
	.word @ref18
	.byte $ff,$08
	.word @ref18
	.byte $ff,$08
	.word @ref18
	.byte $ff,$08
	.word @ref26
	.byte $ff,$08
	.word @ref27
	.byte $ff,$08
	.word @ref27
	.byte $ff,$08
	.word @ref27
	.byte $ff,$08
	.word @ref27
	.byte $ff,$08
	.word @ref27
@song0ch1loop:
	.byte $00
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@ref32:
	.byte $88,$63,$62,$85,$61,$60,$85,$5d,$5c,$85,$5d,$59,$55,$55,$55,$53,$52,$81
@ref33:
	.byte $8a,$60,$95,$60,$64,$9b,$64,$56,$83,$56,$64,$93,$64,$68,$93,$6f,$6b,$69,$64,$81
@ref34:
	.byte $64,$60,$93,$60,$64,$93,$64,$56,$cb
@ref35:
	.byte $60,$95,$60,$64,$9b,$64,$56,$83,$56,$64,$93,$64,$68,$93,$6f,$6b,$69,$64,$81
	.byte $ff,$09
	.word @ref34
@ref36:
	.byte $00,$f9,$83
@ref37:
	.byte $00,$b5,$8c,$56,$85,$6e,$8d,$6e,$85,$64,$8d,$68,$85,$64,$85,$60,$85
@ref38:
	.byte $00,$f9,$83
@ref39:
	.byte $6e,$bd,$00,$85,$68,$85,$00,$85,$64,$85,$00,$85,$60,$85,$00,$85,$5a,$85
@ref40:
	.byte $af,$00,$cd
@ref41:
	.byte $d7,$56,$8d,$6e,$00,$6e,$00,$6e,$00,$72,$00,$78,$00,$72,$00
	.byte $ff,$13
	.word @ref33
@ref42:
	.byte $60,$95,$60,$64,$93,$64,$56,$ab,$8c,$56,$00,$6e,$00,$83,$6e,$00,$6e,$00,$72,$00,$78,$00,$78,$00
	.byte $ff,$13
	.word @ref33
@ref43:
	.byte $60,$95,$60,$64,$93,$64,$56,$ab,$8c,$56,$00,$6e,$00,$83,$6e,$00,$6e,$00,$6e,$00,$6e,$00,$6e,$00
@ref44:
	.byte $00,$f9,$83
@ref45:
	.byte $00,$b5,$56,$85,$6e,$8d,$6e,$85,$64,$8d,$68,$85,$64,$85,$60,$85
@ref46:
	.byte $00,$f9,$83
@ref47:
	.byte $bf,$64,$85,$64,$85,$64,$85,$68,$85,$64,$9d
@ref48:
	.byte $00,$f9,$83
@ref49:
	.byte $d7,$56,$95,$56,$00,$5a,$00,$60,$00,$5a,$00
	.byte $ff,$13
	.word @ref33
	.byte $ff,$17
	.word @ref42
	.byte $ff,$13
	.word @ref33
	.byte $ff,$17
	.word @ref43
	.byte $ff,$13
	.word @ref33
	.byte $ff,$17
	.word @ref42
	.byte $ff,$13
	.word @ref33
	.byte $ff,$17
	.word @ref43
@ref50:
	.byte $00,$f9,$83
@ref51:
	.byte $00,$f9,$83
@ref52:
	.byte $00,$f9,$83
@ref53:
	.byte $00,$f9,$83
@ref54:
	.byte $00,$f9,$83
@ref55:
	.byte $00,$f9,$83
@ref56:
	.byte $00,$f9,$83
@ref57:
	.byte $00,$f9,$83
@ref58:
	.byte $00,$f9,$83
	.byte $ff,$10
	.word @ref45
@ref59:
	.byte $00,$f9,$83
	.byte $ff,$0b
	.word @ref47
@ref60:
	.byte $00,$f9,$83
	.byte $ff,$0b
	.word @ref49
	.byte $ff,$13
	.word @ref33
	.byte $ff,$17
	.word @ref42
	.byte $ff,$13
	.word @ref33
	.byte $ff,$17
	.word @ref43
	.byte $ff,$13
	.word @ref33
	.byte $ff,$17
	.word @ref42
	.byte $ff,$13
	.word @ref33
	.byte $ff,$17
	.word @ref43
@ref61:
	.byte $00,$f9,$83
@ref62:
	.byte $00,$f9,$83
@ref63:
	.byte $00,$f9,$83
@ref64:
	.byte $00,$f9,$83
@ref65:
	.byte $00,$f9,$83
@ref66:
	.byte $00,$f9,$83
@song0ch2loop:
	.byte $00
	.byte $fd
	.word @song0ch2loop

@song0ch3:
	.byte $fb, $06
@ref67:
	.byte $fb,$04,$81,$fb,$03,$81,$fb,$04,$86,$50,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$50,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$50,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$50,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$50,$fb,$03,$81,$fb,$04,$50,$fb,$03,$81
@ref68:
	.byte $fb,$04,$84,$56,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$86,$50,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$84,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$86,$50,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$84,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$86,$50,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$84,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$86,$50,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$50,$fb,$03,$81,$fb,$04,$84,$56,$fb,$03,$81
@ref69:
	.byte $fb,$04,$56,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$86,$50,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$84,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$86,$50,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$84,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$86,$50,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$84,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$86,$50,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$50,$fb,$03,$81,$fb,$04,$84,$56,$fb,$03,$81
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
@ref70:
	.byte $fb,$04,$56,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$86,$50,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$84,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$86,$50,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$84,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$86,$50,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$84,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$86,$50,$fb,$03,$81,$fb,$04,$50,$fb,$03,$81,$fb,$04,$50,$fb,$03,$81,$fb,$04,$50,$fb,$03,$81
	.byte $ff,$40
	.word @ref68
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref70
	.byte $ff,$40
	.word @ref68
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref70
	.byte $ff,$40
	.word @ref68
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref70
	.byte $ff,$40
	.word @ref68
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref70
	.byte $ff,$40
	.word @ref68
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref70
	.byte $ff,$40
	.word @ref68
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref70
	.byte $ff,$40
	.word @ref68
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref70
	.byte $ff,$40
	.word @ref68
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref70
	.byte $ff,$40
	.word @ref68
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
	.byte $ff,$40
	.word @ref69
@ref71:
	.byte $fb,$04,$56,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$86,$50,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$84,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$86,$50,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$84,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$86,$50,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$84,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81,$fb,$04,$86,$50,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$84,$56,$fb,$03,$81,$fb,$04,$56,$fb,$03,$81
	.byte $ff,$40
	.word @ref71
@song0ch3loop:
	.byte $00
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@ref72:
	.byte $33,$36,$85,$33,$36,$85,$33,$36,$85,$33,$37,$33,$33,$33,$37,$36,$81
@ref73:
	.byte $32,$8d,$36,$8d,$32,$8d,$36,$8d,$32,$8d,$36,$8d,$32,$8d,$36,$85,$36,$85
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
@ref74:
	.byte $32,$8d,$36,$8d,$32,$8d,$36,$8d,$32,$8d,$36,$8d,$32,$85,$36,$85,$37,$37,$37,$36,$81
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$15
	.word @ref74
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$15
	.word @ref74
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$15
	.word @ref74
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$15
	.word @ref74
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$15
	.word @ref74
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$15
	.word @ref74
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$15
	.word @ref74
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$15
	.word @ref74
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
	.byte $ff,$12
	.word @ref73
@ref75:
	.byte $8f,$36,$9d,$36,$9d,$36,$9d,$36,$8d
	.byte $ff,$09
	.word @ref75
@song0ch4loop:
	.byte $00
	.byte $fd
	.word @song0ch4loop

